name: Make requirements
run-name: Make ${{ inputs.packages }} requirements on ${{ inputs.python_version }}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to make requirements"
        required: true
        type: string
      python_version:
        description: "Python version"
        required: true
        type: string
        default: "3.12"

permissions:
  contents: write

jobs:
  make-requirements:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    name: Make ${{ inputs.packages }} requirements
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          pip install pipgrip
      - name: Make ${{ inputs.packages }} requirements
        run: python make-req.py ${{ inputs.packages }}
      - name: Setup git author
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git pull
          git add packages
          git commit -m "update packages ${{ inputs.packages }}"
          git push
