name: Make requirements

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to make requirements"
        required: true
        type: string

permissions:
  contents: write

jobs:
  make-requirements:
    runs-on: ubuntu-latest
    name: Make ${{ inputs.packages }} requirements
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make ${{ inputs.packages }} requirements
        run: python make-req.py ${{ inputs.packages }}
      - name: Setup git author
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git add packages
          git commit -m "update packages ${{ inputs.packages }}"
          git push
